# x=True
# print(x)
# print(type(x))
# print(x+10)
# print(False+10)
# print(bool(8))
# print(bool(0))
# print(bool(-1))
# print(bool(0.0))
# print(bool("北京欢迎你"))
# print(bool(""))
# print(bool(False))
# print(bool(True))
# print(bool(None))
# x=10
# y=3
# z=x/y
# print(z,type(z))
# print("float类型转换为整数类型：",int(3.14))
# print("将int转换为float类型：",float(10))
# print("将字符串类型转换为int类型",int("100")+int("200"))
# print(int("100")+int("200"))
# #print(int("18a"))
# #print(int("3.14"))
# print(float("3.14a.159"))
# print(ord("杨"))
# print(chr(26472))
print("十进制转换为十六进制：",hex(32))
print("十进制转换为八进制：",oct(16))
print("十进制转换为二进制：",bin(8))