# s=" admin     "
# print(s)
# print(len(s))
# print('*'*20)
# result=s.strip()
# print(result)
# print(len(result))
# result=s.lstrip()
# print(result)
# print(len(result))
# result=s.rstrip()
# print(result)
# print(len(result))
# s="hello world"
# result=s.center(30)
# print(result)
# print(len(result))
# result=s.ljust(30)
# print(result)
# print(len(result))
# result=s.rjust(30)
# print(result)
# print(len(result))
# s="hello"
# s2="world"
# result=s+s2
# print(result)
# print("李泽说：%s"%"今天天气真好")
# name="赵丽颖"
# age=18
# result="美女{}今年{}岁".format(name,age)
# print(result)
# result="美女{}今年{}岁，我也{}岁了".format(name,age,age)
# print(result)
# result="美女{0}今年{1}岁，我也{1}岁了".format(name,age)
# print(result)
# result="美女{name}今年{age}岁，我也{age}岁了".format(name="赵丽颖",age="18")
# print(result)
# print('*'*20)
# print("美女"+str(name)+"今年"+str(age)+"岁，我也"+str(age)+"岁了")
# name="小明"
# score_chinese=98
# score_math=100
# result="{0}数学考了{1}分，语文考了{2}分，英语也考了{2}分".format(name,score_math,score_chinese)
# print(result)
# result="{}数学考了{}分，语文考了{}分，英语也考了{}分".format(name,score_math,score_chinese,score_chinese)
# print(result)